name: C++ Compile Test Currency_Conversion

on:
  push:
    branches:
      - main
    paths:
      - 'Currency_Conversion/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Currency_Conversion/**'    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile C++ files with g++ (C++20)
        run: |
          for file in Currency_Conversion/*.cpp
          do
            g++ -std=c++20 -o "${file%.cpp}" "$file"
          done
        working-directory: ${{ github.workspace }}

