name: C++ Compile Test SHA2_256

on:
  push:
    branches:
      - main
    paths:
      - 'SHA2_256/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile C++ files with g++ (C++20)
        run: |
          for file in SHA2_256/*.cpp
          do
            g++ -std=c++20 -o "${file%.cpp}" "$file"
          done
        working-directory: ${{ github.workspace }}